export type CartItem = {
    id: string;
    productId: string;
    variantId?: string;
    slug: string;
    title: string;
    rentDates: string;
    rentalStart?: string;
    rentalEnd?: string;
    rentDatesLabel?: string;
    rentalDays?: number;
    pricePerDay: string;
    size: string;
    color: string;
    quantity: number;
    price: number;
    depositRequirement?: number;
    image: string;
    selected: boolean;
    shopId?: string;
    shopName?: string;
    availableStock?: number;
};
